#!/usr/bin/env bash

sudo true

# wsl.exe -d NixOS --mount --vhd 'W:\@Packages\WSL\LinuxProjects.vhdx' --bare
gsudo wsl.exe -d NixOS --mount --vhd 'D:\Data\WSL\LinuxProjects.vhdx' --bare

sleep 5

for i in `seq 1 10`; do
  # sudo mount -t drvfs 'E:' /mnt/e
  sudo mount -a;
  if [[ $? == 0 ]]; then
    break
  fi
  sleep 1;
done
