# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/home/kuriko/Projects" =
    { device = "/dev/disk/by-uuid/59eb1b70-d82d-4d62-9622-284d1515f849";
    fsType = "ext4";
  };

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      ocl-icd
      intel-ocl
      intel-compute-runtime
      # (lib.LowPrio khronos-ocl-icd-loader)
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
