# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: let
  # mesa_new = pkgs.mesa;
  # mesa_new = pkgs.mesa.overrideAttrs (oldAttrs: {
  #   haveDozen = true;
  #   mesonFlags = oldAttrs.mesonFlags ++ [
  #     (lib.mesonOption "gallium-drivers" (lib.concatStringsSep "," [
  #       "d3d12" # WSL emulated GPU (aka Dozen)
  #       "nouveau" # Nvidia
  #       "radeonsi" # new AMD (GCN+)
  #       "swrast" # software renderer (aka LLVMPipe)
  #       "svga" # VMWare virtualized GPU
  #       "virgl" # QEMU virtualized GPU (aka VirGL)
  #       "zink" # generic OpenGL over Vulkan, experimental
  #     ]))
  #     (lib.mesonOption "vulkan-drivers" (lib.concatStringsSep "," [
  #       "amd" # AMD (aka RADV)
  #       "microsoft-experimental" # WSL virtualized GPU (aka DZN/Dozen)
  #       "nouveau" # Nouveau (aka NVK)
  #       "swrast" # software renderer (aka Lavapipe)
  #     ]))
  #   ];
  # });
in {
  imports = [];

  boot.initrd.availableKernelModules = [];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  boot.supportedFilesystems = ["btrfs"];

  boot.tmp.useTmpfs = false;

  fileSystems = {
    "/home/kuriko/Projects" = {
      device = "/dev/disk/by-uuid/e0e5f930-1dee-4179-a2bd-897e7b8b733b";
      fsType = "btrfs";
      options = [
        "compress=zstd:1" # 开启透明压缩，等级1 (最佳性能/压缩比)
        "noatime" # 读取文件不更新访问时间 (大幅减少写操作)
        "space_cache=v2" # Btrfs 专用：优化空闲空间管理 (推荐开启)
        "discard=async" # SSD 优化：异步 TRIM (对 WSL 虚拟盘也有帮助)
        "nofail" # 必须保留：防止磁盘未挂载时导致系统启动失败
      ];
    };
  };

  environment.variables = {
    # WSL libs need to find stdc++.so.6 and libssl.so to work
    # LD_LIBRARY_PATH = "/usr/lib/wsl/lib";
    # LD_LIBRARY_PATH = "/usr/lib/wsl/lib:${pkgs.stdenv.cc.cc.lib}/lib/:${pkgs.openssl.out}/lib";

    # MESA_D3D12_DEFAULT_ADAPTER_NAME = "NVIDIA";
  };

  environment.systemPackages = with pkgs; [
    btrfs-progs
    util-linux
  ];

  # wsl-utils enables this automatically
  # hardware.graphics = {
  #   enable = false;
  #   extraPackages = with pkgs; [
  #     # mesa.drivers
  #     # rocmPackages.clr.icd
  #
  #     # nvidia-vaapi-driver
  #     # intel-vaapi-driver
  #     # amdvlk
  #
  #     # khronos-ocl-icd-loader
  #     # intel-ocl
  #     # intel-compute-runtime
  #     # vaapiIntel
  #     # vaapiVdpau
  #     # libvdpau-va-gl
  #
  #     # ocl-icd
  #   ];
  # };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
