name: "update flakes"

on:
    # push:
    # workflow_dispatch:
    # schedule:
    #     - cron: "0 10,23 * * *"

permissions:
    actions: write
    contents: write
    pull-requests: write
    statuses: read

jobs:
    update-flakes:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            timestamp: "N/A"
        steps:
            - uses: szenius/set-timezone@v2.0
              with:
                timezoneLinux: "Asia/Shanghai"

            - uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install Nix
              uses: cachix/install-nix-action@v31
              with:
                github_access_token: ${{ secrets.GITHUB_TOKEN }}
                set_as_trusted_user: true
                extra_nix_config: |
                    keep-env-derivations = true
                    keep-outputs = true

            - name: Restore and save Nix store
              uses: nix-community/cache-nix-action@v6
              with:
                    # restore and save a cache using this key
                    primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
                    # if there's no cache hit, restore a cache by this prefix
                    restore-prefixes-first-match: nix-${{ runner.os }}-
                    # collect garbage until the Nix store size (in bytes) is at most this number
                    # before trying to save a new cache
                    # 1G = 1073741824
                    gc-max-store-size-linux: 2G
                    # do purge caches
                    purge: true
                    # purge all versions of the cache
                    purge-prefixes: nix-${{ runner.os }}-
                    # created more than this number of seconds ago
                    purge-created: 0
                    # or, last accessed more than this number of seconds ago
                    # relative to the start of the `Post Restore and save Nix store` phase
                    purge-last-accessed: 0
                    # except any version with the key that is the same as the `primary-key`
                    purge-primary-key: never

            - run: nix flake update

            - name: Generate timestamp
              id: timestamp
              run: echo "timestamp=$(date +'%y%m%d.%H%M')" >> $GITHUB_ENV

            - name: Commit Changes
              uses: EndBug/add-and-commit@v9.1.4
              with:
                committer_name: GitHub Actions
                committer_email: 41898282+github-actions[bot]@users.noreply.github.com
                message: "Auto update"
